### PR TITLE
WIP: Add flag to check if proto.lock is up to date

### PR DESCRIPTION
**Pull request by lihalite**
For #101.

I'm putting this up as a WIP because I'm not super familiar with Go anymore, and this feels rather janky to me - perhaps there's a better way? Or if it makes sense, I'll fill out the unit tests.

### CODE REVIEW

**Comment by nilslice** [comment]
@lihalite - thank you! I will take a look through this and add comments if needed. I am about to catch a flight though, so I may not be able to get through this all in full until later this week.

**Comment by lihalite** [comment]
Awesome, no rush - thanks for this great tool!

**Comment by lihalite** [comment]
Rebased on top of master.

**Comment by nilslice** [comment]
@lihalite - thank you for keeping this updated! I have only just been able to start looking at the PR, and want to make sure I give it a throughout look-through.

**Comment by lihalite** [comment]
Rebased this again, just to keep things up-to-date.

**Comment by nilslice** [comment]
Hi @lihalite - 

I will _finally_ have some time to review this PR over the weekend and next week :) sorry for such a delay. It's a fairly sizable chunk of code, and since its is mostly reflection-based, I am having a hard time following exactly what's going on. 

Would you mind adding some more comments to the code? And/or adding an overview in the PR about what the approach is. 

Also, the tests seem to operate on a pretty sparse data set. This is fine for accuracy, but I'm wondering how the reflection code handles very large proto sets. Have you been able to test this feature on your projects of decently large scale? If not, this is a great repository for testing performance: https://github.com/googleapis/googleapis -- mind giving it a try?

**Comment by lihalite** [comment]
Thanks for the follow-up! I can definitely clarify things, I just got back from vacation so I may need a bit of time to catch up on my backlog 😅 

We haven't put this into production yet. I can test it on a large project, though.

**Comment by lihalite** [comment]
Rebased and added some comments, plus fixed a few UI things.

The general approach is basically to handwrite comparator functions for each of the structs in the lockfile. There is reflection used for one helper method, which does an order-ignoring comparison of two slices.

Turns out emicklei/proto cannot parse some of the files in Googleapis (under the Google ads tree). Removing those, here's a basic performance test:

```
$ time ./protolock status
[protolock]: proto.lock file is not up-to-date with sources
[protolock]: run 'protolock commit'

real	0m0.435s
user	0m0.489s
sys	0m0.054s
```

**Comment by nilslice** [comment]
> Turns out emicklei/proto cannot parse some of the files in Googleapis (under the Google ads tree). 

Would you be able to share the errors in a separate issue? We can explore this and see if a PR to upstream could be made to fix, or provide some specific feedback to emicklei/proto about the issue. 

---

Thank you for the explanation and for running this against some test code -- really appreciate your help. I'm just running through my own tests now and will comment if there is more for me to understand, or merge in and release ASAP!

**Comment by lihalite** [comment]
https://github.com/nilslice/protolock/issues/108 for the parsing issue.

**Pull request merged**
